version: '4'
services:
  mysql:
    image: mysql:8.0.31
    container_name: fuel_quota
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: SVish@123
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql
